INSERT INTO CATEGORY (title) VALUES ('고기반찬');
INSERT INTO CATEGORY (title) VALUES ('아이반찬');
INSERT INTO CATEGORY (title) VALUES ('국,찌개');
INSERT INTO CATEGORY (title) VALUES ('밑반찬');
INSERT INTO CATEGORY (title) VALUES ('생선반찬');
INSERT INTO CATEGORY (title) VALUES ('간식');
INSERT INTO CATEGORY (title) VALUES ('기타');
