insert into normal_user (email, name, deleted, address, phone_no) values ('athomazet0@deviantart.com', '청도 짭조름한 손맛의 송씨 할아버지', false, '5832 Service Hill', '846-102-1930');
insert into normal_user (email, name, deleted, address, phone_no) values ('bference1@jimdo.com', '남양주 담백한 맛을 잘 내는 안씨 아주머니', false, '78 Dovetail Pass', '764-232-9530');
insert into normal_user (email, name, deleted, address, phone_no) values ('cmurrie2@msu.edu', '영동 매콤한 국물 전문가 권씨 아주머니', false, '5605 Evergreen Pass', '215-126-1876');
insert into normal_user (email, name, deleted, address, phone_no) values ('ciacomo3@amazonaws.com', '괴산 담백한 국물 전문가 신씨 삼촌', false, '9197 Hoepker Park', '332-129-5276');
insert into normal_user (email, name, deleted, address, phone_no) values ('kolifard4@sbwire.com', '거제 되직한 요리를 좋아하는 한씨 삼촌', false, '30 Paget Crossing', '668-834-4524');
insert into normal_user (email, name, deleted, address, phone_no) values ('iyve5@skype.com', '보성 씁쓰름한 요리를 좋아하는 최씨 할아버지', false, '1 Granby Drive', '879-900-0061');
insert into normal_user (email, name, deleted, address, phone_no) values ('cpentercost6@freewebs.com', '청주 매콤한 맛을 잘 내는 홍씨 아저씨', false, '2 Charing Cross Street', '846-320-1602');
insert into normal_user (email, name, deleted, address, phone_no) values ('wlafflina7@elpais.com', '왜관 고들고들한 손맛의 임씨 할머니', false, '7604 Sunbrook Terrace', '616-318-8553');
insert into normal_user (email, name, deleted, address, phone_no) values ('aboldock8@wunderground.com', '안동 달달한 요리를 좋아하는 정씨 이모', false, '83 Brentwood Park', '953-364-3550');
insert into normal_user (email, name, deleted, address, phone_no) values ('kboldra9@sohu.com', '남제주 달콤한 밥을 잘 짓는 장씨 할아버지', false, '6871 Carey Trail', '229-304-5513');
insert into normal_user (email, name, deleted, address, phone_no) values ('nclotworthya@canalblog.com', '남제주 오동통한 밥을 잘 짓는 박씨 아주머니', false, '3 Clyde Gallagher Way', '932-405-1343');
insert into normal_user (email, name, deleted, address, phone_no) values ('lenrigob@mlb.com', '남원 개운한 요리를 좋아하는 전씨 아주머니', false, '0 Del Sol Center', '944-179-2076');
insert into normal_user (email, name, deleted, address, phone_no) values ('apoulsomc@tiny.cc', '여천 달짝지근한 요리를 좋아하는 강씨 아주머니', false, '5919 Crownhardt Court', '731-383-2564');
insert into normal_user (email, name, deleted, address, phone_no) values ('isalzburgerd@google.de', '인천 간간한 음식을 잘 하는 전씨 할아버지', false, '0 Coolidge Terrace', '202-462-1318');
insert into normal_user (email, name, deleted, address, phone_no) values ('bbyfforde@webeden.co.uk', '영월 달콤한 밥을 잘 짓는 홍씨 아주머니', false, '39 Division Circle', '437-511-9578');
insert into normal_user (email, name, deleted, address, phone_no) values ('severixf@bigcartel.com', '과천 달짝지근한 손맛의 정씨 할머니', false, '3365 Sheridan Junction', '545-800-9856');
insert into normal_user (email, name, deleted, address, phone_no) values ('rdelgadog@imageshack.us', '안산 짭짤한 국물 전문가 박씨 아저씨', false, '786 Kim Terrace', '703-319-8636');
insert into normal_user (email, name, deleted, address, phone_no) values ('ljerischh@scribd.com', '상주 되직한 맛을 잘 내는 서씨 할머니', false, '9044 Sloan Place', '200-965-1415');
insert into normal_user (email, name, deleted, address, phone_no) values ('btookeyi@joomla.org', '강릉 오동통한 국물 전문가 김씨 아주머니', false, '8 Leroy Pass', '338-208-3808');
insert into normal_user (email, name, deleted, address, phone_no) values ('mboijj@msn.com', '목포 달달한 요리를 좋아하는 김씨 이모', false, '52359 Wayridge Lane', '178-776-1573');
insert into normal_user (email, name, deleted, address, phone_no) values ('hfourcadek@barnesandnoble.com', '장흥 바삭바삭한 밥을 잘 짓는 한씨 할아버지', false, '18696 Dunning Circle', '319-656-3670');
insert into normal_user (email, name, deleted, address, phone_no) values ('bdrakel@reverbnation.com', '춘천 짭짤한 밥을 잘 짓는 최씨 이모', false, '449 Canary Trail', '717-724-3998');
insert into normal_user (email, name, deleted, address, phone_no) values ('ewildorm@clickbank.net', '사천 새콤달콤한 반찬을 즐겨 만드는 한씨 할머니', false, '34452 Gerald Plaza', '582-977-2263');
insert into normal_user (email, name, deleted, address, phone_no) values ('bivoryn@istockphoto.com', '군산 매콤한 국물 전문가 강씨 아저씨', false, '62 Mifflin Circle', '769-188-5518');
insert into normal_user (email, name, deleted, address, phone_no) values ('kstyano@163.com', '상주 바삭바삭한 음식을 잘 하는 조씨 할아버지', false, '56 Forest Dale Point', '327-504-6960');
insert into normal_user (email, name, deleted, address, phone_no) values ('kchealep@people.com.cn', '남해 짭조름한 밥을 잘 짓는 박씨 아저씨', false, '520 Bay Court', '952-220-7024');
insert into normal_user (email, name, deleted, address, phone_no) values ('selementq@ibm.com', '산청 짭짤한 요리를 좋아하는 안씨 삼촌', false, '418 Meadow Ridge Pass', '492-690-4420');
insert into normal_user (email, name, deleted, address, phone_no) values ('bparsallr@mail.ru', '인제 간간한 맛을 잘 내는 조씨 할아버지', false, '240 Del Mar Crossing', '739-298-0079');
insert into normal_user (email, name, deleted, address, phone_no) values ('zvertigans@flickr.com', '창원 담백한 밥을 잘 짓는 신씨 삼촌', false, '49 Graedel Junction', '249-627-2191');
insert into normal_user (email, name, deleted, address, phone_no) values ('bgrigoriant@bandcamp.com', '의정부 바삭바삭한 요리를 좋아하는 장씨 아주머니', false, '01370 Crowley Lane', '710-720-0141')
insert into normal_user (email, name, deleted, address, phone_no, password) values ('a', '6조의 충실한 맛집 테스트 계정', false, '53575 Talmadge Terrace', '448-130-7169', '$2a$10$wcN5tM.qDTynm/yNS/8KC.rTGAMMQq4QhURkkvBzR1mXElb2kcjmq');

insert into category (title, category_image_url) VALUES ('전체보기','https://s3.ap-northeast-2.amazonaws.com/moduchan-img/static/%E1%84%87%E1%85%A2%E1%84%83%E1%85%A1%E1%86%AF%E1%84%8B%E1%85%B5.png');
insert into category (title, category_image_url) VALUES ('밑반찬','https://s3.ap-northeast-2.amazonaws.com/moduchan-img/static/%E1%84%86%E1%85%B5%E1%87%80%E1%84%87%E1%85%A1%E1%86%AB%E1%84%8E%E1%85%A1%E1%86%AB.png');
insert into category (title, category_image_url) VALUES ('국,찌개','https://s3.ap-northeast-2.amazonaws.com/moduchan-img/static/%E1%84%80%E1%85%AE%E1%86%A8.png');
insert into category (title, category_image_url) VALUES ('고기반찬','https://s3.ap-northeast-2.amazonaws.com/moduchan-img/static/%E1%84%80%E1%85%A9%E1%84%80%E1%85%B5.png');
insert into category (title, category_image_url) VALUES ('생선반찬','https://s3.ap-northeast-2.amazonaws.com/moduchan-img/static/%E1%84%89%E1%85%A2%E1%86%BC%E1%84%89%E1%85%A5%E1%86%AB.png');
insert into category (title, category_image_url) VALUES ('아이반찬','https://s3.ap-northeast-2.amazonaws.com/moduchan-img/static/%E1%84%8B%E1%85%A1%E1%84%80%E1%85%B5%E1%84%87%E1%85%A1%E1%86%AB%E1%84%8E%E1%85%A1%E1%86%AB.png');
insert into category (title, category_image_url) VALUES ('간식','https://s3.ap-northeast-2.amazonaws.com/moduchan-img/static/%E1%84%83%E1%85%B5%E1%84%8C%E1%85%A5%E1%84%90%E1%85%B3.png');
insert into category (title, category_image_url) VALUES ('기타','https://s3.ap-northeast-2.amazonaws.com/moduchan-img/static/%E1%84%80%E1%85%B5%E1%84%90%E1%85%A1.png');
